# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Set build number.
name: $(Date:yyMMdd)$(Rev:rrr)

  
# Set pipeline variables
variables:
- name: myBuildType
  ${{ if eq(variables['Build.Reason'], 'PullRequest')}}:
    value: 'pr'
  ${{ if and( ne(variables['Build.Reason'], 'PullRequest'), eq( variables['Build.SourceBranchName'], 'master')) }}:  
    value: 'master'
  ${{ if and( ne(variables['Build.Reason'], 'PullRequest'), eq( variables['Build.SourceBranchName'], 'develop')) }}:  
    value: 'develop'
  ${{ if and( ne(variables['Build.Reason'], 'PullRequest'), ne( variables['Build.SourceBranchName'], 'develop'), ne( variables['Build.SourceBranchName'], 'master'))  }}:  
    value: 'unknown'
    
trigger:
- develop

jobs:
  - job: WindozeBuild
    timeoutInMinutes: 180
    displayName: 'Run Windows build script'
    pool:
      name: Default
      demands:
        - agent.name -equals Picasso
        
    steps:
      - checkout: self
        clean: true
        fetchDepth: 1
        path: colony.core

      - script: cd && top\build_all_windoze.bat $(myBuildType) $(Build.BuildNumber)
        displayName: 'Windoze build'
  - job: autoOff
    displayName: Auto-off
    steps:
      - checkout: none
      - task: AzureCLI@2
        inputs:
          azureSubscription: 