name: Windows Build

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  # Visual Studio Compiler Windows build job
  vc_windows_build:
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    name: Visual Studio Compiler Windows Build
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Python setup
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      # Ninja setup
      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: '1.11.1'

      # MSVC setup (For a Git hosted runner - always uses the latest version of MSVC)
      - uses: ilammy/msvc-dev-cmd@v1.4.1
        with:
          arch: x86 

      #- name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3

      # Build PRs
      - name: Run build script - for PRs
        if: github.event_name == 'pull_request'
        run: |
          echo "Running build script for PRs..."
          .\top\gha_vc12.bat ${{ github.run_number }} 

      # Build Stable branches
      - name: Run build script - for stable branches
        if: github.event_name != 'pull_request'
        run: |
          echo "Running build script for stable branches..."
          .\top\gha_vc12.bat ${{ github.run_number }} ${{ github.head_ref }}


  # MinGW  Compiler Windows build job
  mingw_64_windows_build:
    name: MinGW Compiler Windows 64bit Build
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Python setup
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      # Ninja setup
      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: '1.11.1'

      # MinGW setup
      - name: MinGW compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-10.3.0

      #- name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3

      # Build PRs
      - name: Run build script - for PRs
        if: github.event_name == 'pull_request'
        run: |
          echo "Running build script for PRs..."
          .\top\gha_mingw-64.bat ${{ github.run_number }} 

      # Build Stable branches
      - name: Run build script - for stable branches
        if: github.event_name != 'pull_request'
        run: |
          echo "Running build script for stable branches..."
          .\top\gha_mingw-64.bat ${{ github.run_number }} ${{ github.head_ref }}

  # GCC Compiler Linux build job
  gcc_linux_build:
    name: GCC Compiler Linux Build
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Python setup
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      # Ninja setup
      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: '1.11.1'

      # # MinGW setup
      # - name: MinGW compiler
      #   uses: rlalik/setup-cpp-compiler@master
      #   with:
      #     compiler: gcc-10.3.0

      #- name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3

      # Installs and Run Doxygen
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.10.0"
      
      # Check for Doxygen errors (use the run_doxygen.py to check for errors)
      - name: Check for Doxygen errors
        run: |
          echo "Checking for Doxygen errors..."
          cd ./top
          ./run_doxygen.py ${{ github.head_ref }} ${{ github.run_number }}
        
      # Build PRs
      - name: Run build script - for PRs
        if: github.event_name == 'pull_request'
        run: |
          echo "Running build script for PRs..."
          ./top/gha_linux-gcc.sh ${{ github.run_number }} 

      # Build Stable branches
      - name: Run build script - for stable branches
        if: github.event_name != 'pull_request'
        run: |
          echo "Running build script for stable branches..."
          ./top/gha_linux-gcc.sh ${{ github.run_number }} ${{ github.head_ref }}
      
      # Publish Doxygen documentation (but only when building main branch)
      - name: Publish Doxygen documentation
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
