name: Windows Build

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Python setup
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      # MSVC setup
      - uses: ilammy/msvc-dev-cmd@v1.4.1
        with:
          toolset: 19.39.33523


      - name: Set up environment
        run: |
          echo "Setting up environment..."
          # Add any environment setup commands here if needed

      - name: Run build script
        run: |
          .\top\test_all_windoze.bat ${{ github.run_number }} ${{ github.ref }}
